/*
The MIT License

Copyright (c) 2012 Universidad Politecnica de Madrid

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.*/
var XMLHttpRequest = require("./../vendor/xmlhttprequest").XMLHttpRequest;
var JSTACK=JSTACK||{};JSTACK.VERSION="0.1";JSTACK.AUTHORS="GING";JSTACK.Comm=function(c,e){var g;g=function(c,d,a,b,f,j){var g,i;g=new XMLHttpRequest;g.open(c,d,!0);g.setRequestHeader("Content-Type","application/json");g.setRequestHeader("Accept","application/json");g.onreadystatechange=function(){if(4===g.readyState)switch(g.status){case 100:case 200:case 201:case 202:case 203:case 204:case 205:i=e;g.responseText!==e&&""!==g.responseText&&(i=JSON.parse(g.responseText));f(i);break;case 400:j("400 Bad Request");break;case 401:j("401 Unauthorized");break;case 403:j("403 Forbidden");
break;default:j(g.status+" Error")}};b!==e&&g.setRequestHeader("X-Auth-Token",b);a!==e?(c=JSON.stringify(a),g.send(c)):g.send()};return{get:function(c,d,a,b){g("GET",c,e,d,a,b)},post:function(c,d,a,b,f){g("POST",c,d,a,b,f)},put:function(c,d,a,b,f){g("PUT",c,d,a,b,f)},del:function(c,d,a,b){g("DELETE",c,e,d,a,b)}}}(JSTACK);JSTACK.Utils=function(c){var e,g;e=function(c){var d="",a,b,c=c.replace(/\r\n/g,"\n");for(a=0;a<c.length;a+=1)b=c.charCodeAt(a),128>b?d+=String.fromCharCode(b):(127<b&&2048>b?d+=String.fromCharCode(b>>6|192):(d+=String.fromCharCode(b>>12|224),d+=String.fromCharCode(b>>6&63|128)),d+=String.fromCharCode(b&63|128));return d};g=function(c){for(var d="",a=0,b=0,f=0,j=0;a<c.length;)b=c.charCodeAt(a),128>b?(d+=String.fromCharCode(b),a+=1):191<b&&224>b?(f=c.charCodeAt(a+1),d+=String.fromCharCode((b&31)<<
6|f&63),a+=2):(f=c.charCodeAt(a+1),j=c.charCodeAt(a+2),d+=String.fromCharCode((b&15)<<12|(f&63)<<6|j&63),a+=3);return d};return{encode:function(g){for(var d="",a,b,f,j,k,i,l=0,g=e(g);l<g.length;)a=g.charCodeAt(l+=1),b=g.charCodeAt(l+=1),f=g.charCodeAt(l+=1),j=a>>2,a=(a&3)<<4|b>>4,k=(b&15)<<2|f>>6,i=f&63,isNaN(b)?k=i=64:isNaN(f)&&(i=64),d=d+c.Utils.keyStr.charAt(j)+Base64.keyStr.charAt(a)+c.Utils.keyStr.charAt(k)+Base64.keyStr.charAt(i);return d},decode:function(e){for(var d="",a,b,f,j,k,i=0,e=e.replace(/[^A-Za-z0-9\+\/\=]/g,
"");i<e.length;)a=c.Utils.keyStr.indexOf(e.charAt(i+=1)),b=c.Utils.keyStr.indexOf(e.charAt(i+=1)),j=c.Utils.keyStr.indexOf(e.charAt(i+=1)),k=c.Utils.keyStr.indexOf(e.charAt(i+=1)),a=a<<2|b>>4,b=(b&15)<<4|j>>2,f=(j&3)<<6|k,d+=String.fromCharCode(a),64!==j&&(d+=String.fromCharCode(b)),64!==k&&(d+=String.fromCharCode(f));return d=g(d)}}}(JSTACK);JSTACK.Keystone=function(c,e){var g,h;h={DISCONNECTED:0,AUTHENTICATING:1,AUTHENTICATED:2,AUTHENTICATION_ERROR:3};g={url:e,currentstate:e,access:e,token:e};return{STATES:h,params:g,init:function(c){g.url=c;g.access=e;g.token=e;g.currentstate=h.DISCONNECTED},authenticate:function(d,a,b,f,j,k){var i={},i=b!==e?{auth:{token:{id:b}}}:{auth:{passwordCredentials:{username:d,password:a}}};f!==e&&(i.auth.tenantId=f);g.currentstate=h.AUTHENTICATING;c.Comm.post(g.url+"tokens",i,e,function(a){g.currentstate=
c.Keystone.STATES.AUTHENTICATED;g.access=a.access;g.token=g.access.token.id;j!==e&&j(a)},function(a){g.currentstate=h.AUTHENTICATION_ERROR;k(a)})},gettenants:function(d){g.currentstate===c.Keystone.STATES.AUTHENTICATED&&c.Comm.get(g.url+"tenants",g.token,function(a){d!==e&&d(a)},function(a){throw Error(a);})},getservice:function(c){var a,b;if(g.currentstate!==h.AUTHENTICATED)return e;for(a in g.access.serviceCatalog)if(g.access.serviceCatalog[a]!==e&&(b=g.access.serviceCatalog[a],c===b.type))return b;
return e},getservicelist:function(){return g.currentstate!==h.AUTHENTICATED?e:g.access.serviceCatalog}}}(JSTACK);JSTACK.Nova=function(c,e){var g,h,d;g=e;h=function(){return c.Keystone!==e&&c.Keystone.params.currentstate===c.Keystone.STATES.AUTHENTICATED?(g=c.Keystone.getservice("compute").endpoints[0][c.Nova.params.endpointType],!0):!1};d=function(a,b,f,j){h()&&(a=g+"/servers/"+a+"/action",c.Comm.post(a,b,c.Keystone.params.token,function(a){j!==e&&j(a)},function(a){throw Error(a);}))};return{configure:function(a){if("adminUrl"===a||"publicUrl"===a||"internalUrl"===a)c.Nova.params.endpointType=a},getserverlist:function(a,
b,f){var j;h()&&(j=g+"/servers",a!==e&&a&&(j+="/detail"),b&&(j+="?all_tenants="+b),c.Comm.get(j,c.Keystone.params.token,function(a){f!==e&&f(a)},function(a){throw Error(a);}))},getserverdetail:function(a,b){var f;h()&&(f=g+"/servers/"+a,c.Comm.get(f,c.Keystone.params.token,function(a){b!==e&&b(a)},function(a){throw Error(a);}))},getserverips:function(a,b,f){h()&&(a=g+"/servers/"+a+"/ips",b!==e&&(a+="/"+b),c.Comm.get(a,c.Keystone.params.token,function(a){f!==e&&f(a)},function(a){throw Error(a);}))},
updateserver:function(a,b,f){h()&&(a=g+"/servers/"+a,b!==e&&c.Comm.put(a,{server:{name:b}},c.Keystone.params.token,function(a){f!==e&&f(a)},function(a){throw Error(a);}))},createserver:function(a,b,f,d,k,i,l,m,n,o){var q=[],p;if(h()){a={server:{name:a,imageRef:b,flavorRef:f}};d!==e&&(a.server.key_name=d);k!==e&&(a.server.user_data=c.Utils.encode(k));if(i!==e){for(p in i)i[p]!==e&&(d={name:i[p]},q.push(d));a.server.security_groups=q}l===e&&(l=1);a.server.min_count=l;m===e&&(m=1);a.server.max_count=
m;n!==e&&(a.server.availability_zone=c.Utils.encode(n));c.Comm.post(g+"/servers",a,c.Keystone.params.token,function(a){o!==e&&o(a)},function(a){throw Error(a);})}},deleteserver:function(a,b){var f;h()&&(f=g+"/servers/"+a,c.Comm.del(f,c.Keystone.params.token,function(a){b!==e&&b(a)},function(a){throw Error(a);}))},changepasswordserver:function(a,b,f){b!==e&&d(a,{changePassword:{adminPass:b}},f)},rebootserverhard:function(a,b){d(a,{reboot:{type:"HARD"}},b)},rebootserversoft:function(a,b){d(a,{reboot:{type:"SOFT"}},
b)},resizeserver:function(a,b,f){d(a,{resize:{flavorRef:b}},f)},confirmresizedserver:function(a,b){d(a,{confirmResize:null},b)},revertresizedserver:function(a,b){d(a,{revertResize:null},b)},startserver:function(a,b){d(a,{"os-start":null},b)},stopserver:function(a,b){d(a,{"os-stop":null},b)},pauseserver:function(a,b){d(a,{pause:null},b)},unpauseserver:function(a,b){d(a,{unpause:null},b)},suspendserver:function(a,b){d(a,{suspend:null},b)},resumeserver:function(a,b){d(a,{resume:null},b)},createimage:function(a,
b,f,c){b={createImage:{name:b}};b.createImage.metadata={};f!==e&&(b.createImage.metadata=f);d(a,b,c)},getflavorlist:function(a,b){var f;h()&&(f=g+"/flavors",a!==e&&a&&(f+="/detail"),c.Comm.get(f,c.Keystone.params.token,function(a){b!==e&&b(a)},function(a){throw Error(a);}))},getflavordetail:function(a,b){var f;h()&&(f=g+"/flavors/"+a,c.Comm.get(f,c.Keystone.params.token,function(a){b!==e&&b(a)},function(a){throw Error(a);}))},createflavor:function(a,b,f,d,k,i,l,m,n){var o;h()&&(o=g+"/flavors",a={flavor:{name:a,
ram:b,vcpus:f,disk:d,id:k,swap:0,"OS-FLV-EXT-DATA:ephemeral":0,rxtx_factor:0}},i!==e&&(a.flavor["OS-FLV-EXT-DATA:ephemeral"]=i),l!==e&&(a.flavor.swap=l),m!==e&&(a.flavor.rxtx_factor=m),c.Comm.post(o,a,c.Keystone.params.token,function(a){n!==e&&n(a)},function(a){throw Error(a);}))},deleteflavor:function(a,b){var f;h()&&(f=g+"/flavors/"+a,c.Comm.del(f,c.Keystone.params.token,function(a){b!==e&&b(a)},function(a){throw Error(a);}))},getimagelist:function(a,b){var f;h()&&(f=g+"/images",a!==e&&a&&(f+="/detail"),
c.Comm.get(f,c.Keystone.params.token,function(a){b!==e&&b(a)},function(a){throw Error(a);}))},getimagedetail:function(a,b){var f;h()&&(f=g+"/images/"+a,c.Comm.get(f,c.Keystone.params.token,function(a){b!==e&&b(a)},function(a){throw Error(a);}))},deleteimage:function(a,b){var f;h()&&(f=g+"/images/"+a,c.Comm.del(f,c.Keystone.params.token,function(a){b!==e&&b(a)},function(a){throw Error(a);}))},getkeypairlist:function(a){var b;h()&&(b=g+"/os-keypairs",c.Comm.get(b,c.Keystone.params.token,function(b){a!==
e&&a(b)},function(a){throw Error(a);}))},createkeypair:function(a,b,f){var d;h()&&(d=g+"/os-keypairs",a={keypair:{name:a}},b!==e&&(a.keypair.public_key=b),c.Comm.post(d,a,c.Keystone.params.token,function(a){f!==e&&f(a)},function(a){throw Error(a);}))},deletekeypair:function(a,b){var f;h()&&(f=g+"/os-keypairs/"+a,c.Comm.del(f,c.Keystone.params.token,function(a){b!==e&&b(a)},function(a){throw Error(a);}))},getvncconsole:function(a,b,f){if(h()){if(b===e||!b)b="novnc";d(a,{"os-getVNCConsole":{type:b}},
null,f)}},getconsoleoutput:function(a,b,f){if(h()){if(b===e||!b)b=35;d(a,{"os-getConsoleOutput":{length:b}},null,f)}},getattachedvolumes:function(a,b){var f;h()&&(f=g+"/servers/"+a+"/os-volume_attachments",c.Comm.get(f,c.Keystone.params.token,function(a){b!==e&&b(a)},function(a){throw Error(a);}))},attachvolume:function(a,b,f,d){h()&&(a=g+"/servers/"+a+"/os-volume_attachments",b===e||f===e||c.Comm.post(a,{volumeAttachment:{volumeId:b,device:f}},c.Keystone.params.token,function(a){d!==e&&d(a)},function(a){throw Error(a);
}))},detachvolume:function(a,b,f){h()&&(a=g+"/servers/"+a+"/os-volume_attachments/"+b,b!==e&&c.Comm.del(a,c.Keystone.params.token,function(a){f!==e&&f(a)},function(a){throw Error(a);}))},getattachedvolume:function(a,b,f){h()&&(a=g+"/servers/"+a+"/os-volume_attachments/"+b,b!==e&&c.Comm.get(a,c.Keystone.params.token,function(a){f!==e&&f(a)},function(a){throw Error(a);}))}}}(JSTACK);JSTACK.Nova.Volume=function(c,e){var g,h;g=e;h=function(){return c.Keystone!==e&&c.Keystone.params.currentstate===c.Keystone.STATES.AUTHENTICATED?(g=c.Keystone.getservice("volume").endpoints[0][c.Nova.Volume.params.endpointType],!0):!1};return{configure:function(d){if("adminUrl"===d||"publicUrl"===d||"internalUrl"===d)c.Nova.Volume.params.endpointType=d},getvolumelist:function(d,a){var b;h()&&(b=g+"/volumes",d!==e&&d&&(b+="/detail"),c.Comm.get(b,c.Keystone.params.token,function(b){a!==e&&a(b)},function(a){throw Error(a);
}))},createvolume:function(d,a,b,f){h()&&(d={volume:{size:d}},a!==e&&(d.volume.display_name=a),b!==e&&(d.volume.display_description=b),c.Comm.post(g+"/volumes",d,c.Keystone.params.token,function(a){f!==e&&f(a)},function(a){throw Error(a);}))},deletevolume:function(d,a){var b;h()&&(b=g+"/volumes/"+d,c.Comm.del(b,c.Keystone.params.token,function(b){a!==e&&a(b)},function(a){throw Error(a);}))},getvolume:function(d,a){var b;h()&&(b=g+"/volumes/"+d,c.Comm.get(b,c.Keystone.params.token,function(b){a!==
e&&a(b)},function(a){throw Error(a);}))},getsnapshotlist:function(d,a){var b;h()&&(b=g+"/snapshots",d!==e&&d&&(b+="/detail"),c.Comm.get(b,c.Keystone.params.token,function(b){a!==e&&a(b)},function(a){throw Error(a);}))},createsnapshot:function(d,a,b,f){h()&&(d={snapshot:{volume_id:d,force:!0}},a!==e&&(d.snapshot.display_name=a),b!==e&&(d.snapshot.display_description=b),c.Comm.post(g+"/snapshots",d,c.Keystone.params.token,function(a){f!==e&&f(a)},function(a){throw Error(a);}))},deletesnapshot:function(d,
a){var b;h()&&(b=g+"/snapshots/"+d,c.Comm.del(b,c.Keystone.params.token,function(b){a!==e&&a(b)},function(a){throw Error(a);}))},getsnapshot:function(d,a){var b;h()&&(b=g+"/snapshots/"+d,c.Comm.get(b,c.Keystone.params.token,function(b){a!==e&&a(b)},function(a){throw Error(a);}))}}}(JSTACK);JSTACK.Glance=function(c,e){var g,h;g=e;h=function(){return c.Keystone!==e&&c.Keystone.params.currentstate===c.Keystone.STATES.AUTHENTICATED?(g=c.Keystone.getservice("image").endpoints[0][c.Glance.params.endpointType],!0):!1};return{configure:function(d){if("adminUrl"===d||"publicUrl"===d||"internalUrl"===d)c.Glance.params.endpointType=d},getimagelist:function(d,a){var b;h()&&(b=g+"/images",d!==e&&d&&(b+="/detail"),c.Comm.get(b,c.Keystone.params.token,function(b){a!==e&&a(b)},function(a){throw Error(a);
}))}}}(JSTACK);
module.exports = JSTACK;
